# Generated by Django 4.1.5 on 2023-04-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_category_user_alter_transaction_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_credit',
        ),
    ]
