# Generated by Django 4.1.5 on 2023-04-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='account',
        ),
        migrations.AddField(
            model_name='category',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
