# Generated by Django 4.1.5 on 2023-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_account_name_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
